<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!-- Generated by TLex (build Aug 12 2015 20:56:50) -->
<!-- Generated on Wed Nov 18 11:57:55 2015 -->
<!-- TshwaneDJe HLT - XML version 1.10 -->
<!-- ExportListValuesByText: OFF -->
<!-- UseZeroWidthSpacesToPreventConversionOfPCDataToElements: OFF -->
<!DOCTYPE tshwanelexicon [
<!ELEMENT tshwanelexicon (dtd,styleset*,Dictionary)>
<!ELEMENT dtd (specialtypes?,dtdlist*,xreftypes*)>
<!ELEMENT dtdlist (dtdlistitem*,listlabelset*)>
<!ELEMENT dtdlistitem EMPTY>
<!ELEMENT listlabelset (listlabel*)>
<!ELEMENT listlabel EMPTY>
<!ELEMENT xreftypes (xreftype*,xreflabelset*)>
<!ELEMENT xreftype EMPTY>
<!ELEMENT xreflabelset (xreflabel*)>
<!ELEMENT xreflabel EMPTY>
<!ELEMENT specialtypes (special*)>
<!ELEMENT special EMPTY>
<!ELEMENT styleset (order,style*)>
<!ELEMENT order (order_element*)>
<!ELEMENT order_element (order_item*)>
<!ELEMENT order_item EMPTY>
<!ELEMENT style (style_autonumber*)>
<!ELEMENT style_autonumber EMPTY>
<!ELEMENT Dictionary (Language+)>
<!ELEMENT Language (Lemma*)>
<!ELEMENT Lemma (DialForm*,Loan*,References*,Sense*,VerbTheme*,Nonverb*,Subentry*)>
<!ELEMENT Sense (Loan*,References*,Definition*,Grammar*,Translation*,Biological*,Location*,Encyclopedia*,SourceForm*,Source*,TE*,Example*,Sense*)>
<!ELEMENT DialForm EMPTY>
<!ELEMENT Example EMPTY>
<!ELEMENT VerbTheme (VerbForm*,Loan*,References*,Sense*,Subentry*,VerbTheme*,Nonverb*)>
<!ELEMENT VerbForm EMPTY>
<!ELEMENT Nonverb (DialForm*,References*,Sense*,Nonverb*)>
<!ELEMENT Subentry (DialForm*,Loan*,References*,Sense*,Subentry*)>
<!ELEMENT Loan EMPTY>
<!ELEMENT Definition EMPTY>
<!ELEMENT Biological EMPTY>
<!ELEMENT Location EMPTY>
<!ELEMENT Translation EMPTY>
<!ELEMENT Grammar EMPTY>
<!ELEMENT Encyclopedia EMPTY>
<!ELEMENT Source EMPTY>
<!ELEMENT SourceForm EMPTY>
<!ELEMENT TE EMPTY>
<!ELEMENT References (reflemma*)>
<!ELEMENT reflemma (refsense*)>
<!ELEMENT refsense EMPTY>
<!ATTLIST dtdlist id CDATA #REQUIRED>
<!ATTLIST dtdlist name CDATA #REQUIRED>
<!ATTLIST dtdlistitem id CDATA #REQUIRED>
<!ATTLIST dtdlistitem name CDATA #REQUIRED>
<!ATTLIST listlabelset name CDATA #REQUIRED>
<!ATTLIST listlabel listitemid CDATA #REQUIRED>
<!ATTLIST listlabel name CDATA #REQUIRED>
<!ATTLIST xreftype id CDATA #REQUIRED>
<!ATTLIST xreftype name CDATA #REQUIRED>
<!ATTLIST xreflabelset name CDATA #REQUIRED>
<!ATTLIST xreflabel xreftypeid CDATA #REQUIRED>
<!ATTLIST xreflabel labels CDATA #REQUIRED>
<!ATTLIST xreflabel labelp CDATA #REQUIRED>
<!ATTLIST reflemma lemmaid CDATA #REQUIRED>
<!ATTLIST reflemma type CDATA #REQUIRED>
<!ATTLIST refsense senseid CDATA #REQUIRED>
<!ATTLIST special type CDATA #REQUIRED>
<!ATTLIST special section CDATA #REQUIRED>
<!ATTLIST special attr CDATA #REQUIRED>
<!ATTLIST special elem CDATA #REQUIRED>
<!ATTLIST styleset name CDATA #IMPLIED>
<!ATTLIST order_element elementname CDATA #REQUIRED>
<!ATTLIST order_item type CDATA #REQUIRED>
<!ATTLIST order_item name CDATA #REQUIRED>
<!ATTLIST order_item visible CDATA #REQUIRED>
<!ATTLIST style type CDATA #IMPLIED>
<!ATTLIST style elementname CDATA #IMPLIED>
<!ATTLIST style attributename CDATA #IMPLIED>
<!ATTLIST style style CDATA #IMPLIED>
<!ATTLIST style font CDATA #IMPLIED>
<!ATTLIST style fontsize CDATA #IMPLIED>
<!ATTLIST style bold CDATA #IMPLIED>
<!ATTLIST style italic CDATA #IMPLIED>
<!ATTLIST style underline CDATA #IMPLIED>
<!ATTLIST style superscript CDATA #IMPLIED>
<!ATTLIST style subscript CDATA #IMPLIED>
<!ATTLIST style smallcaps CDATA #IMPLIED>
<!ATTLIST style caps CDATA #IMPLIED>
<!ATTLIST style colourf CDATA #IMPLIED>
<!ATTLIST style colourb CDATA #IMPLIED>
<!ATTLIST style beforei CDATA #IMPLIED>
<!ATTLIST style afteri CDATA #IMPLIED>
<!ATTLIST style beforeo CDATA #IMPLIED>
<!ATTLIST style aftero CDATA #IMPLIED>
<!ATTLIST style beforeg CDATA #IMPLIED>
<!ATTLIST style afterg CDATA #IMPLIED>
<!ATTLIST style between CDATA #IMPLIED>
<!ATTLIST style_autonumber type CDATA #IMPLIED>
<!ATTLIST style_autonumber always CDATA #IMPLIED>
<!ATTLIST style_autonumber breadth CDATA #IMPLIED>
<!ATTLIST style_autonumber depth CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Dictionary Name CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Dictionary Description CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Dictionary CreatedBy CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Dictionary Copyright CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Dictionary URL CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Dictionary SoundPath CDATA #IMPLIED>
<!ATTLIST Dictionary id CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Language Name CDATA #IMPLIED>
<!-- ATTDATA NDATA,,#IMPLIED,ltr -->
<!ATTLIST Language Options CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Language AlphabetQuicklinks CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Language SearchScript CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Language ClickScript CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Language xml:lang CDATA #IMPLIED>
<!ATTLIST Language id CDATA #IMPLIED>
<!-- ATTDATA NDATA,,#IMPLIED,ltr -->
<!ATTLIST Lemma Incomplete CDATA #IMPLIED>
<!-- ATTDATA LDATA,Possessor,#IMPLIED,ltr -->
<!ATTLIST Lemma Possessor CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#REQUIRED,ltr -->
<!ATTLIST Lemma LemmaSign CDATA #REQUIRED>
<!-- ATTDATA NDATA,,#IMPLIED,ltr -->
<!ATTLIST Lemma HomonymNumber CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Lemma LemmaVar CDATA #IMPLIED>
<!-- ATTDATA LDATA,Root shape,#IMPLIED,ltr -->
<!ATTLIST Lemma RootShape CDATA #IMPLIED>
<!-- ATTDATA LDATA,Variable root,#IMPLIED,ltr -->
<!ATTLIST Lemma RootVar CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Lemma Pronunciation CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Lemma Deriv CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Lemma Gloss CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Lemma Etymology CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Lemma Comment CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Lemma Notes CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#DATECREATED,ltr -->
<!ATTLIST Lemma Created CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#DATECHANGED,ltr -->
<!ATTLIST Lemma Modified CDATA #IMPLIED>
<!-- ATTDATA LNDATA,Usage label,#IMPLIED,ltr -->
<!ATTLIST Lemma UsageLabel CDATA #IMPLIED>
<!-- ATTDATA LNDATA,Part of speech,#IMPLIED,ltr -->
<!ATTLIST Lemma PartOfSpeech CDATA #IMPLIED>
<!ATTLIST Lemma id CDATA #IMPLIED>
<!-- ATTDATA NDATA,,#AUTONUMBER,ltr -->
<!ATTLIST Sense SenseNumber CDATA #IMPLIED>
<!-- ATTDATA LDATA,Part of speech,#IMPLIED,ltr -->
<!ATTLIST Sense PartOfSpeech CDATA #IMPLIED>
<!-- ATTDATA LNDATA,Usage label,#IMPLIED,ltr -->
<!ATTLIST Sense UsageLabel CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Sense Notes CDATA #IMPLIED>
<!ATTLIST Sense id CDATA #IMPLIED>
<!-- ATTDATA LDATA,Dialect,#IMPLIED,ltr -->
<!ATTLIST DialForm Dialect CDATA #IMPLIED>
<!-- ATTDATA LDATA,Possessor,#IMPLIED,ltr -->
<!ATTLIST DialForm Possessor CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST DialForm Form CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST DialForm Pronunciation CDATA #IMPLIED>
<!ATTLIST DialForm id CDATA #IMPLIED>
<!-- ATTDATA NDATA,,#AUTONUMBER,ltr -->
<!ATTLIST Example ExampleNumber CDATA #IMPLIED>
<!-- ATTDATA LDATA,Dialect,#IMPLIED,ltr -->
<!ATTLIST Example Dialect CDATA #IMPLIED>
<!-- ATTDATA LDATA,Example type,#IMPLIED,ltr -->
<!ATTLIST Example ExampleType CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Example Example CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Example Translation CDATA #IMPLIED>
<!-- ATTDATA LDATA,Source,#IMPLIED,ltr -->
<!ATTLIST Example Source CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Example Page CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Example Comment CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Example Notes CDATA #IMPLIED>
<!ATTLIST Example id CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST VerbTheme LemmaSign CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST VerbTheme LemmaVar CDATA #IMPLIED>
<!-- ATTDATA LDATA,Verb mode,#IMPLIED,ltr -->
<!ATTLIST VerbTheme LemmaMode CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST VerbTheme Adjunct CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST VerbTheme Theme CDATA #IMPLIED>
<!-- ATTDATA LDATA,Conjugation class,#IMPLIED,ltr -->
<!ATTLIST VerbTheme ConjClass CDATA #IMPLIED>
<!-- ATTDATA LDATA,Imperfective type,#IMPLIED,ltr -->
<!ATTLIST VerbTheme ImpfvType CDATA #IMPLIED>
<!-- ATTDATA LDATA,Theme category,#IMPLIED,ltr -->
<!ATTLIST VerbTheme ThemeCateg CDATA #IMPLIED>
<!-- ATTDATA LDATA,Classifier S,#IMPLIED,ltr -->
<!ATTLIST VerbTheme Classifier-S CDATA #IMPLIED>
<!-- ATTDATA LDATA,Classifier D,#IMPLIED,ltr -->
<!ATTLIST VerbTheme Classifier-D CDATA #IMPLIED>
<!-- ATTDATA LDATA,Verb valency,#IMPLIED,ltr -->
<!ATTLIST VerbTheme Valency CDATA #IMPLIED>
<!-- ATTDATA LNDATA,Clause subcategorization,#IMPLIED,ltr -->
<!ATTLIST VerbTheme ClauseSubcat CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST VerbTheme NaishStory CDATA #IMPLIED>
<!-- ATTDATA NDATA,,#NORMAL,ltr -->
<!ATTLIST VerbTheme BasicVocab CDATA "0">
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST VerbTheme Notes CDATA #IMPLIED>
<!-- ATTDATA NDATA,,#USERCREATED,ltr -->
<!ATTLIST VerbTheme Created CDATA #IMPLIED>
<!-- ATTDATA NDATA,,#USERCHANGED,ltr -->
<!ATTLIST VerbTheme Modified CDATA #IMPLIED>
<!-- ATTDATA LDATA,Derivation type,#IMPLIED,ltr -->
<!ATTLIST VerbTheme DerivType CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST VerbTheme DerivAdjunct CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST VerbTheme DerivMorph CDATA #IMPLIED>
<!-- ATTDATA LDATA,Conjugation class,#IMPLIED,ltr -->
<!ATTLIST VerbTheme DerivConjClass CDATA #IMPLIED>
<!-- ATTDATA LDATA,Imperfective type,#IMPLIED,ltr -->
<!ATTLIST VerbTheme DerivImpfvType CDATA #IMPLIED>
<!-- ATTDATA LDATA,Theme category,#IMPLIED,ltr -->
<!ATTLIST VerbTheme DerivThemeCateg CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST VerbTheme DerivGloss CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST VerbTheme Etymology CDATA #IMPLIED>
<!ATTLIST VerbTheme id CDATA #IMPLIED>
<!-- ATTDATA LDATA,Dialect,#IMPLIED,ltr -->
<!ATTLIST VerbForm Dialect CDATA #IMPLIED>
<!-- ATTDATA LDATA,Reality,#IMPLIED,ltr -->
<!ATTLIST VerbForm Realis CDATA #IMPLIED>
<!-- ATTDATA LDATA,Epimode,#IMPLIED,ltr -->
<!ATTLIST VerbForm Epimode CDATA #IMPLIED>
<!-- ATTDATA LDATA,Imperfective type,#IMPLIED,ltr -->
<!ATTLIST VerbForm ImpfvType CDATA #IMPLIED>
<!-- ATTDATA LDATA,Theme category,#IMPLIED,ltr -->
<!ATTLIST VerbForm ThemeCateg CDATA #IMPLIED>
<!-- ATTDATA LDATA,Verb mode,#IMPLIED,ltr -->
<!ATTLIST VerbForm Mode CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST VerbForm Form CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST VerbForm Gloss CDATA #IMPLIED>
<!ATTLIST VerbForm id CDATA #IMPLIED>
<!-- ATTDATA LDATA,Possessor,#IMPLIED,ltr -->
<!ATTLIST Nonverb Possessor CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Nonverb LemmaSign CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Nonverb LemmaVar CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Nonverb Notes CDATA #IMPLIED>
<!ATTLIST Nonverb id CDATA #IMPLIED>
<!-- ATTDATA LDATA,Possessor,#IMPLIED,ltr -->
<!ATTLIST Subentry Possessor CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Subentry LemmaSign CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Subentry LemmaVar CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Subentry Pronunciation CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Subentry Deriv CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Subentry Gloss CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Subentry Etymology CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Subentry Comment CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Subentry Notes CDATA #IMPLIED>
<!-- ATTDATA NDATA,,#USERCREATED,ltr -->
<!ATTLIST Subentry Created CDATA #IMPLIED>
<!-- ATTDATA NDATA,,#USERCHANGED,ltr -->
<!ATTLIST Subentry Modified CDATA #IMPLIED>
<!-- ATTDATA LNDATA,Usage label,#IMPLIED,ltr -->
<!ATTLIST Subentry UsageLabel CDATA #IMPLIED>
<!-- ATTDATA LNDATA,Part of speech,#IMPLIED,ltr -->
<!ATTLIST Subentry PartOfSpeech CDATA #IMPLIED>
<!ATTLIST Subentry id CDATA #IMPLIED>
<!-- ATTDATA LDATA,Loan direction,#IMPLIED,ltr -->
<!ATTLIST Loan Direction CDATA #IMPLIED>
<!-- ATTDATA LDATA,Language,#IMPLIED,ltr -->
<!ATTLIST Loan Language CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Loan Form CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Loan Meaning CDATA #IMPLIED>
<!ATTLIST Loan id CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#REQUIRED,ltr -->
<!ATTLIST Definition Definition CDATA #REQUIRED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Definition Comment CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Definition Notes CDATA #IMPLIED>
<!ATTLIST Definition id CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#REQUIRED,ltr -->
<!ATTLIST Biological Genus CDATA #REQUIRED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Biological Species CDATA #IMPLIED>
<!-- ATTDATA LDATA,Infraspecific type,#IMPLIED,ltr -->
<!ATTLIST Biological InfraType CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Biological Infraspecific CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Biological Authority CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Biological Year CDATA #IMPLIED>
<!-- ATTDATA LNDATA,Biological class,#IMPLIED,ltr -->
<!ATTLIST Biological SemClass CDATA #IMPLIED>
<!ATTLIST Biological id CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Location Latitude CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Location Longitude CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Location Zoom CDATA #IMPLIED>
<!ATTLIST Location id CDATA #IMPLIED>
<!-- ATTDATA LDATA,Language,#IMPLIED,ltr -->
<!ATTLIST Translation Language CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Translation Form CDATA #IMPLIED>
<!ATTLIST Translation id CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Grammar Text CDATA #IMPLIED>
<!ATTLIST Grammar id CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Encyclopedia Text CDATA #IMPLIED>
<!ATTLIST Encyclopedia id CDATA #IMPLIED>
<!-- ATTDATA LDATA,Source,#IMPLIED,ltr -->
<!ATTLIST Source Source CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Source Page CDATA #IMPLIED>
<!ATTLIST Source id CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST SourceForm Form CDATA #IMPLIED>
<!-- ATTDATA LDATA,Source,#IMPLIED,ltr -->
<!ATTLIST SourceForm Source CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST SourceForm Page CDATA #IMPLIED>
<!ATTLIST SourceForm id CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#REQUIRED,ltr -->
<!ATTLIST TE TE CDATA #REQUIRED>
<!ATTLIST TE id CDATA #IMPLIED>
<!ATTLIST References id CDATA #IMPLIED>
<!ENTITY ndash "–">
<!ENTITY mdash "—">
<!ENTITY lsquo "‘">
<!ENTITY rsquo "’">
<!ENTITY ldquo "“">
<!ENTITY rdquo "”">
<!ENTITY bull "•">
<!ENTITY hellip "…">
<!ENTITY trade "™">
<!ENTITY dagger "†">
<!ENTITY Dagger "‡">
<!ENTITY lsaquo "‹">
<!ENTITY rsaquo "›">
<!ENTITY sp " ">
<!ENTITY nbsp " ">
<!ENTITY ensp " ">
<!ENTITY emsp " ">
<!ENTITY pound "£">
<!ENTITY copy "©">
<!ENTITY reg "®">
<!ENTITY tshwanelex__list__seperator ";">
]>
<tshwanelexicon>
<dtd>
	<specialtypes>
		<special type="0" section="2" attr="TE" elem="TE"/>
		<special type="2" section="2" attr="" elem="Sense"/>
		<special type="3" section="2" attr="LemmaSign" elem="Lemma"/>
		<special type="4" section="2" attr="Notes" elem="Lemma"/>
		<special type="4" section="2" attr="Notes" elem="Example"/>
		<special type="4" section="2" attr="Notes" elem="Definition"/>
		<special type="4" section="2" attr="Notes" elem="VerbTheme"/>
		<special type="4" section="2" attr="Notes" elem="Sense"/>
		<special type="4" section="2" attr="Notes" elem="Nonverb"/>
		<special type="4" section="2" attr="Notes" elem="Subentry"/>
		<special type="0" section="3" attr="TE" elem="TE"/>
		<special type="2" section="3" attr="" elem="Sense"/>
		<special type="3" section="3" attr="LemmaSign" elem="Lemma"/>
		<special type="4" section="3" attr="Notes" elem="Lemma"/>
	</specialtypes>
	<dtdlist id="1" name="Usage label">
		<dtdlistitem id="189" name="archaic"/>
		<dtdlistitem id="190" name="rare"/>
		<dtdlistitem id="191" name="rude"/>
		<dtdlistitem id="192" name="slang"/>
		<dtdlistitem id="215" name="innovative"/>
		<dtdlistitem id="260" name="obsolete"/>
		<dtdlistitem id="273" name="uncertain"/>
		<dtdlistitem id="304" name="humorous"/>
		<listlabelset name="English">
			<listlabel listitemid="189" name="archaic"/>
			<listlabel listitemid="190" name="rare"/>
			<listlabel listitemid="191" name="rude"/>
			<listlabel listitemid="192" name="slang"/>
			<listlabel listitemid="215" name="innovative"/>
			<listlabel listitemid="260" name="obsolete"/>
			<listlabel listitemid="273" name="uncertain"/>
			<listlabel listitemid="304" name="humorous"/>
		</listlabelset>
		<listlabelset name="Abbreviated">
			<listlabel listitemid="189" name="arch"/>
			<listlabel listitemid="190" name="rare"/>
			<listlabel listitemid="191" name="rude"/>
			<listlabel listitemid="192" name="slang"/>
			<listlabel listitemid="215" name="innov"/>
			<listlabel listitemid="260" name="obs"/>
			<listlabel listitemid="273" name="uncert"/>
			<listlabel listitemid="304" name="hum"/>
		</listlabelset>
	</dtdlist>
	<dtdlist id="2" name="Part of speech">
		<dtdlistitem id="3" name="noun"/>
		<dtdlistitem id="23" name="noun alienable"/>
		<dtdlistitem id="24" name="noun inalienable"/>
		<dtdlistitem id="307" name="noun relational"/>
		<dtdlistitem id="308" name="noun possessed"/>
		<dtdlistitem id="193" name="noun compound psv"/>
		<dtdlistitem id="194" name="noun compound"/>
		<dtdlistitem id="42" name="ethnonym"/>
		<dtdlistitem id="43" name="name place"/>
		<dtdlistitem id="44" name="name personal"/>
		<dtdlistitem id="248" name="name clan"/>
		<dtdlistitem id="277" name="name month"/>
		<dtdlistitem id="276" name="name other"/>
		<dtdlistitem id="8" name="adjective pre"/>
		<dtdlistitem id="25" name="adjective post"/>
		<dtdlistitem id="9" name="adverb"/>
		<dtdlistitem id="45" name="particle"/>
		<dtdlistitem id="11" name="pronoun"/>
		<dtdlistitem id="196" name="postposition"/>
		<dtdlistitem id="255" name="postposition phrase"/>
		<dtdlistitem id="264" name="wh-word"/>
		<dtdlistitem id="251" name="phrase"/>
		<dtdlistitem id="263" name="noun phrase"/>
		<dtdlistitem id="262" name="relativized phrase"/>
		<dtdlistitem id="50" name="suffix"/>
		<dtdlistitem id="46" name="suffix verbal"/>
		<dtdlistitem id="48" name="suffix nominal"/>
		<dtdlistitem id="51" name="prefix"/>
		<dtdlistitem id="47" name="prefix verbal"/>
		<dtdlistitem id="49" name="prefix nominal"/>
		<dtdlistitem id="318" name="preverb"/>
		<dtdlistitem id="12" name="conjunction"/>
		<dtdlistitem id="249" name="directional"/>
		<dtdlistitem id="306" name="demonstrative"/>
		<dtdlistitem id="305" name="determiner"/>
		<dtdlistitem id="314" name="numeral"/>
		<dtdlistitem id="13" name="interjection"/>
		<dtdlistitem id="15" name="idiom"/>
		<dtdlistitem id="16" name="proverb"/>
		<dtdlistitem id="10" name="abbreviation"/>
		<listlabelset name="English">
			<listlabel listitemid="3" name="noun"/>
			<listlabel listitemid="23" name="alienable noun"/>
			<listlabel listitemid="24" name="inalienable noun"/>
			<listlabel listitemid="307" name="relational noun"/>
			<listlabel listitemid="308" name="possessed noun"/>
			<listlabel listitemid="193" name="possessive compound noun"/>
			<listlabel listitemid="194" name="compound noun"/>
			<listlabel listitemid="42" name="ethnonym"/>
			<listlabel listitemid="43" name="placename"/>
			<listlabel listitemid="44" name="personal name"/>
			<listlabel listitemid="248" name="clan name"/>
			<listlabel listitemid="277" name="month name"/>
			<listlabel listitemid="276" name="name"/>
			<listlabel listitemid="8" name="pre-adjective"/>
			<listlabel listitemid="25" name="post-adjective"/>
			<listlabel listitemid="9" name="adverb"/>
			<listlabel listitemid="45" name="particle"/>
			<listlabel listitemid="11" name="pronoun"/>
			<listlabel listitemid="196" name="postposition"/>
			<listlabel listitemid="255" name="postposition phrase"/>
			<listlabel listitemid="264" name="wh-word"/>
			<listlabel listitemid="251" name="phrase"/>
			<listlabel listitemid="263" name="noun phrase"/>
			<listlabel listitemid="262" name="relativized phrase"/>
			<listlabel listitemid="50" name="suffix"/>
			<listlabel listitemid="46" name="verb suffix"/>
			<listlabel listitemid="48" name="noun suffix"/>
			<listlabel listitemid="51" name="prefix"/>
			<listlabel listitemid="47" name="verb prefix"/>
			<listlabel listitemid="49" name="noun prefix"/>
			<listlabel listitemid="318" name="preverb"/>
			<listlabel listitemid="12" name="conjunction"/>
			<listlabel listitemid="249" name="directional"/>
			<listlabel listitemid="306" name="demonstrative"/>
			<listlabel listitemid="305" name="determiner"/>
			<listlabel listitemid="314" name="numeral"/>
			<listlabel listitemid="13" name="interjection"/>
			<listlabel listitemid="15" name="idiom"/>
			<listlabel listitemid="16" name="proverb"/>
			<listlabel listitemid="10" name="abbreviation"/>
		</listlabelset>
		<listlabelset name="Abbreviated">
			<listlabel listitemid="3" name="n"/>
			<listlabel listitemid="23" name="n alb"/>
			<listlabel listitemid="24" name="n inalb"/>
			<listlabel listitemid="307" name="n reln"/>
			<listlabel listitemid="308" name="n pss"/>
			<listlabel listitemid="193" name="n cpd pss"/>
			<listlabel listitemid="194" name="n cpd"/>
			<listlabel listitemid="42" name="ethn"/>
			<listlabel listitemid="43" name="place"/>
			<listlabel listitemid="44" name="pers"/>
			<listlabel listitemid="248" name="clan"/>
			<listlabel listitemid="277" name="month"/>
			<listlabel listitemid="276" name="name"/>
			<listlabel listitemid="8" name="pre-adj"/>
			<listlabel listitemid="25" name="post-adj"/>
			<listlabel listitemid="9" name="adv"/>
			<listlabel listitemid="45" name="pcl"/>
			<listlabel listitemid="11" name="pron"/>
			<listlabel listitemid="196" name="postpn"/>
			<listlabel listitemid="255" name="postpn phr"/>
			<listlabel listitemid="264" name="wh-wd"/>
			<listlabel listitemid="251" name="phr"/>
			<listlabel listitemid="263" name="n phr"/>
			<listlabel listitemid="262" name="rel phr"/>
			<listlabel listitemid="50" name="sfx"/>
			<listlabel listitemid="46" name="v sfx"/>
			<listlabel listitemid="48" name="n sfx"/>
			<listlabel listitemid="51" name="pfx"/>
			<listlabel listitemid="47" name="v pfx"/>
			<listlabel listitemid="49" name="n pfx"/>
			<listlabel listitemid="318" name="pvb"/>
			<listlabel listitemid="12" name="conj"/>
			<listlabel listitemid="249" name="dirn"/>
			<listlabel listitemid="306" name="dem"/>
			<listlabel listitemid="305" name="det"/>
			<listlabel listitemid="314" name="num"/>
			<listlabel listitemid="13" name="interj"/>
			<listlabel listitemid="15" name="idiom"/>
			<listlabel listitemid="16" name="proverb"/>
			<listlabel listitemid="10" name="abbrev"/>
		</listlabelset>
	</dtdlist>
	<dtdlist id="17" name="Conjugation class">
		<dtdlistitem id="102" name="?"/>
		<dtdlistitem id="18" name="∅"/>
		<dtdlistitem id="19" name="na"/>
		<dtdlistitem id="20" name="ga"/>
		<dtdlistitem id="21" name="G̱a"/>
		<dtdlistitem id="257" name="*"/>
		<dtdlistitem id="275" name="∅-ÿ"/>
		<listlabelset name="Abbreviated">
			<listlabel listitemid="102" name="?"/>
			<listlabel listitemid="18" name="∅"/>
			<listlabel listitemid="19" name="na"/>
			<listlabel listitemid="20" name="ga"/>
			<listlabel listitemid="21" name="g̱a"/>
			<listlabel listitemid="257" name="–"/>
			<listlabel listitemid="275" name="∅-ÿ"/>
		</listlabelset>
	</dtdlist>
	<dtdlist id="26" name="Classifier S">
		<dtdlistitem id="27" name="∅"/>
		<dtdlistitem id="28" name="s"/>
		<dtdlistitem id="29" name="l"/>
		<dtdlistitem id="30" name="sh"/>
		<dtdlistitem id="39" name="?"/>
	</dtdlist>
	<dtdlist id="31" name="Classifier D">
		<dtdlistitem id="33" name="−D"/>
		<dtdlistitem id="32" name="+D"/>
		<dtdlistitem id="38" name="±D"/>
		<dtdlistitem id="40" name="?"/>
	</dtdlist>
	<dtdlist id="34" name="Classifier I">
		<dtdlistitem id="36" name="−I"/>
		<dtdlistitem id="35" name="+I"/>
		<dtdlistitem id="37" name="±I"/>
		<dtdlistitem id="41" name="?"/>
	</dtdlist>
	<dtdlist id="52" name="Dialect">
		<dtdlistitem id="53" name="Northern"/>
		<dtdlistitem id="54" name="Southern"/>
		<dtdlistitem id="55" name="Tongass"/>
		<dtdlistitem id="56" name="Inland"/>
		<dtdlistitem id="58" name="Central"/>
		<dtdlistitem id="126" name="Gulf"/>
		<dtdlistitem id="59" name="Transitional"/>
		<dtdlistitem id="60" name="Sanya"/>
		<dtdlistitem id="61" name="Henya"/>
		<dtdlistitem id="123" name="Atlin"/>
		<dtdlistitem id="124" name="Carcross"/>
		<dtdlistitem id="125" name="Teslin"/>
		<dtdlistitem id="198" name="unknown"/>
		<listlabelset name="Abbreviated">
			<listlabel listitemid="53" name="N"/>
			<listlabel listitemid="54" name="S"/>
			<listlabel listitemid="55" name="T"/>
			<listlabel listitemid="56" name="I"/>
			<listlabel listitemid="58" name="C"/>
			<listlabel listitemid="126" name="G"/>
			<listlabel listitemid="59" name="Tr"/>
			<listlabel listitemid="60" name="San"/>
			<listlabel listitemid="61" name="Hen"/>
			<listlabel listitemid="123" name="Atl"/>
			<listlabel listitemid="124" name="Car"/>
			<listlabel listitemid="125" name="Tes"/>
			<listlabel listitemid="198" name="?"/>
		</listlabelset>
	</dtdlist>
	<dtdlist id="69" name="Imperfective type">
		<dtdlistitem id="108" name="?"/>
		<dtdlistitem id="84" name="-ÿ"/>
		<dtdlistitem id="134" name="-h"/>
		<dtdlistitem id="83" name="-ː"/>
		<dtdlistitem id="100" name="-n"/>
		<dtdlistitem id="133" name="-ʼ"/>
		<dtdlistitem id="199" name="invariable"/>
		<dtdlistitem id="77" name="-x̱"/>
		<dtdlistitem id="132" name="-k"/>
		<dtdlistitem id="253" name="-kw"/>
		<dtdlistitem id="136" name="[+I]-…-k"/>
		<dtdlistitem id="137" name="yoo=[+I]-…-k"/>
		<dtdlistitem id="138" name="-ch"/>
		<dtdlistitem id="139" name="DIR=…-ch"/>
		<dtdlistitem id="140" name="-t"/>
		<dtdlistitem id="141" name="-sʼ"/>
		<dtdlistitem id="142" name="-lʼ"/>
		<dtdlistitem id="143" name="-xʼ"/>
		<dtdlistitem id="144" name="-tʼ"/>
		<dtdlistitem id="209" name="-kw-t"/>
		<listlabelset name="Abbreviated">
			<listlabel listitemid="108" name="?"/>
			<listlabel listitemid="84" name="-ÿ"/>
			<listlabel listitemid="134" name="-h"/>
			<listlabel listitemid="83" name="-ː"/>
			<listlabel listitemid="100" name="-n"/>
			<listlabel listitemid="133" name="-ʼ"/>
			<listlabel listitemid="199" name="Inv"/>
			<listlabel listitemid="77" name="-x̱"/>
			<listlabel listitemid="132" name="-k"/>
			<listlabel listitemid="253" name="-kw"/>
			<listlabel listitemid="136" name="[+I]-…-k"/>
			<listlabel listitemid="137" name="yoo=[+I]-…-k"/>
			<listlabel listitemid="138" name="-ch"/>
			<listlabel listitemid="139" name="%sdir%s=…-ch"/>
			<listlabel listitemid="140" name="-t"/>
			<listlabel listitemid="141" name="-sʼ"/>
			<listlabel listitemid="142" name="-lʼ"/>
			<listlabel listitemid="143" name="-xʼ"/>
			<listlabel listitemid="144" name="-tʼ"/>
			<listlabel listitemid="209" name="-kw-t"/>
		</listlabelset>
	</dtdlist>
	<dtdlist id="201" name="Theme category">
		<dtdlistitem id="202" name="stative"/>
		<dtdlistitem id="279" name="stative impfv only"/>
		<dtdlistitem id="214" name="dimensional stative"/>
		<dtdlistitem id="207" name="extensional stative"/>
		<dtdlistitem id="208" name="multipositional stative"/>
		<dtdlistitem id="203" name="active"/>
		<dtdlistitem id="204" name="eventive"/>
		<dtdlistitem id="213" name="involuntary eventive"/>
		<dtdlistitem id="205" name="positional"/>
		<dtdlistitem id="206" name="motion"/>
		<dtdlistitem id="210" name="repetitive"/>
		<dtdlistitem id="278" name="—"/>
		<dtdlistitem id="280" name="?"/>
		<listlabelset name="Abbreviated">
			<listlabel listitemid="202" name="Stv"/>
			<listlabel listitemid="279" name="Stv Impfv only"/>
			<listlabel listitemid="214" name="Dim Stv"/>
			<listlabel listitemid="207" name="Ext Stv"/>
			<listlabel listitemid="208" name="MPos Stv"/>
			<listlabel listitemid="203" name="Act"/>
			<listlabel listitemid="204" name="Evt"/>
			<listlabel listitemid="213" name="Invol Evt"/>
			<listlabel listitemid="205" name="Pos"/>
			<listlabel listitemid="206" name="Mot"/>
			<listlabel listitemid="210" name="Rep"/>
			<listlabel listitemid="278" name="—"/>
			<listlabel listitemid="280" name="?"/>
		</listlabelset>
	</dtdlist>
	<dtdlist id="88" name="Source">
		<dtdlistitem id="127" name="Leer stem collection 1973"/>
		<dtdlistitem id="93" name="Leer verb list 1976"/>
		<dtdlistitem id="94" name="Leer stem list 1978"/>
		<dtdlistitem id="129" name="Leer noun database 1990s"/>
		<dtdlistitem id="89" name="Naish Story 1973"/>
		<dtdlistitem id="195" name="Edwards 2009"/>
		<dtdlistitem id="90" name="Naish 1966"/>
		<dtdlistitem id="91" name="Story 1966"/>
		<dtdlistitem id="92" name="Boas 1917"/>
		<dtdlistitem id="95" name="Dauenhauers 1987"/>
		<dtdlistitem id="128" name="Dauenhauers 1990"/>
		<dtdlistitem id="261" name="Dauenhauers 2002"/>
		<dtdlistitem id="250" name="Leer Hitch Ritter 2001"/>
		<dtdlistitem id="256" name="De Laguna 1972"/>
		<dtdlistitem id="310" name="Swanton 1909"/>
		<dtdlistitem id="312" name="Swanton 1911"/>